compiler:
  solc:
    version: "0.8.17"
    optimizer:
      enabled: true
      runs: 200
    remappings:
    - "@gnosis.pm=node_modules/@gnosis.pm"
    - "@openzeppelin=node_modules/@openzeppelin"

networks:
  development:
    priority_fee: 1 gwei
    cmd_settings:
      evm_version: london
