compiler:
  solc:
    version: "0.8.17"
    optimizer:
      enabled: true
      runs: 200
    remappings:
    - "@gnosis.pm=node_modules/@gnosis.pm"
    - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0
